#
#-- Copyright (C) 2019 dz <dingzhong110@gmail.com>
#


include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for clash
LUCI_DEPENDS:= +clash
PKG_VERSION:=1.03

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
